/// Flutter icons FbIconForFlutter
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FbIconForFlutter
///      fonts:
///       - asset: fonts/FbIconForFlutter.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class FbIconForFlutter {
  FbIconForFlutter._();

  static const _kFontFam = 'FbIconForFlutter';

  static const IconData facebook = const IconData(0xe800, fontFamily: _kFontFam);
}
